apiVersion: apps/v1
kind: Deployment
metadata:
  name: bibliothek-deployment
  labels:
    app: bibliothekkube
spec:
  replicas: 3
  template:
    metadata:
      name: bibliothekkube
      labels:
        app: bibliothekkube
    spec:
      containers:
      - name: bibliothekkube
        image: bibliotheklibacr.azurecr.io/bibliotheklib:v1
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels: 
      app: bibliothekkube
---

apiVersion: v1
kind: Service
metadata:
  name:  bibliothek-service
spec:
  selector:
    app: bibliothekkube
  ports: 
    - port: 8081
  type: LoadBalancer